interface CountryInfo {
  code: string
  emoji: string
  name: string
  unicode: string
}

const countries: Record<string, CountryInfo> = {
  AC: {
    code: 'AC',
    emoji: '🇦🇨',
    name: 'Ascension Island',
    unicode: 'U+1F1E6 U+1F1E8',
  },
  AD: {
    code: 'AD',
    emoji: '🇦🇩',
    name: 'Andorra',
    unicode: 'U+1F1E6 U+1F1E9',
  },
  AE: {
    code: 'AE',
    emoji: '🇦🇪',
    name: 'United Arab Emirates',
    unicode: 'U+1F1E6 U+1F1EA',
  },
  AF: {
    code: 'AF',
    emoji: '🇦🇫',
    name: 'Afghanistan',
    unicode: 'U+1F1E6 U+1F1EB',
  },
  AG: {
    code: 'AG',
    emoji: '🇦🇬',
    name: 'Antigua & Barbuda',
    unicode: 'U+1F1E6 U+1F1EC',
  },
  AI: {
    code: 'AI',
    emoji: '🇦🇮',
    name: 'Anguilla',
    unicode: 'U+1F1E6 U+1F1EE',
  },
  AL: {
    code: 'AL',
    emoji: '🇦🇱',
    name: 'Albania',
    unicode: 'U+1F1E6 U+1F1F1',
  },
  AM: {
    code: 'AM',
    emoji: '🇦🇲',
    name: 'Armenia',
    unicode: 'U+1F1E6 U+1F1F2',
  },
  AO: {
    code: 'AO',
    emoji: '🇦🇴',
    name: 'Angola',
    unicode: 'U+1F1E6 U+1F1F4',
  },
  AQ: {
    code: 'AQ',
    emoji: '🇦🇶',
    name: 'Antarctica',
    unicode: 'U+1F1E6 U+1F1F6',
  },
  AR: {
    code: 'AR',
    emoji: '🇦🇷',
    name: 'Argentina',
    unicode: 'U+1F1E6 U+1F1F7',
  },
  AS: {
    code: 'AS',
    emoji: '🇦🇸',
    name: 'American Samoa',
    unicode: 'U+1F1E6 U+1F1F8',
  },
  AT: {
    code: 'AT',
    emoji: '🇦🇹',
    name: 'Austria',
    unicode: 'U+1F1E6 U+1F1F9',
  },
  AU: {
    code: 'AU',
    emoji: '🇦🇺',
    name: 'Australia',
    unicode: 'U+1F1E6 U+1F1FA',
  },
  AW: {
    code: 'AW',
    emoji: '🇦🇼',
    name: 'Aruba',
    unicode: 'U+1F1E6 U+1F1FC',
  },
  AX: {
    code: 'AX',
    emoji: '🇦🇽',
    name: 'Åland Islands',
    unicode: 'U+1F1E6 U+1F1FD',
  },
  AZ: {
    code: 'AZ',
    emoji: '🇦🇿',
    name: 'Azerbaijan',
    unicode: 'U+1F1E6 U+1F1FF',
  },
  BA: {
    code: 'BA',
    emoji: '🇧🇦',
    name: 'Bosnia & Herzegovina',
    unicode: 'U+1F1E7 U+1F1E6',
  },
  BB: {
    code: 'BB',
    emoji: '🇧🇧',
    name: 'Barbados',
    unicode: 'U+1F1E7 U+1F1E7',
  },
  BD: {
    code: 'BD',
    emoji: '🇧🇩',
    name: 'Bangladesh',
    unicode: 'U+1F1E7 U+1F1E9',
  },
  BE: {
    code: 'BE',
    emoji: '🇧🇪',
    name: 'Belgium',
    unicode: 'U+1F1E7 U+1F1EA',
  },
  BF: {
    code: 'BF',
    emoji: '🇧🇫',
    name: 'Burkina Faso',
    unicode: 'U+1F1E7 U+1F1EB',
  },
  BG: {
    code: 'BG',
    emoji: '🇧🇬',
    name: 'Bulgaria',
    unicode: 'U+1F1E7 U+1F1EC',
  },
  BH: {
    code: 'BH',
    emoji: '🇧🇭',
    name: 'Bahrain',
    unicode: 'U+1F1E7 U+1F1ED',
  },
  BI: {
    code: 'BI',
    emoji: '🇧🇮',
    name: 'Burundi',
    unicode: 'U+1F1E7 U+1F1EE',
  },
  BJ: {
    code: 'BJ',
    emoji: '🇧🇯',
    name: 'Benin',
    unicode: 'U+1F1E7 U+1F1EF',
  },
  BL: {
    code: 'BL',
    emoji: '🇧🇱',
    name: 'St. Barthélemy',
    unicode: 'U+1F1E7 U+1F1F1',
  },
  BM: {
    code: 'BM',
    emoji: '🇧🇲',
    name: 'Bermuda',
    unicode: 'U+1F1E7 U+1F1F2',
  },
  BN: {
    code: 'BN',
    emoji: '🇧🇳',
    name: 'Brunei',
    unicode: 'U+1F1E7 U+1F1F3',
  },
  BO: {
    code: 'BO',
    emoji: '🇧🇴',
    name: 'Bolivia',
    unicode: 'U+1F1E7 U+1F1F4',
  },
  BQ: {
    code: 'BQ',
    emoji: '🇧🇶',
    name: 'Caribbean Netherlands',
    unicode: 'U+1F1E7 U+1F1F6',
  },
  BR: {
    code: 'BR',
    emoji: '🇧🇷',
    name: 'Brazil',
    unicode: 'U+1F1E7 U+1F1F7',
  },
  BS: {
    code: 'BS',
    emoji: '🇧🇸',
    name: 'Bahamas',
    unicode: 'U+1F1E7 U+1F1F8',
  },
  BT: {
    code: 'BT',
    emoji: '🇧🇹',
    name: 'Bhutan',
    unicode: 'U+1F1E7 U+1F1F9',
  },
  BV: {
    code: 'BV',
    emoji: '🇧🇻',
    name: 'Bouvet Island',
    unicode: 'U+1F1E7 U+1F1FB',
  },
  BW: {
    code: 'BW',
    emoji: '🇧🇼',
    name: 'Botswana',
    unicode: 'U+1F1E7 U+1F1FC',
  },
  BY: {
    code: 'BY',
    emoji: '🇧🇾',
    name: 'Belarus',
    unicode: 'U+1F1E7 U+1F1FE',
  },
  BZ: {
    code: 'BZ',
    emoji: '🇧🇿',
    name: 'Belize',
    unicode: 'U+1F1E7 U+1F1FF',
  },
  CA: {
    code: 'CA',
    emoji: '🇨🇦',
    name: 'Canada',
    unicode: 'U+1F1E8 U+1F1E6',
  },
  CC: {
    code: 'CC',
    emoji: '🇨🇨',
    name: 'Cocos (Keeling) Islands',
    unicode: 'U+1F1E8 U+1F1E8',
  },
  CD: {
    code: 'CD',
    emoji: '🇨🇩',
    name: 'Congo - Kinshasa',
    unicode: 'U+1F1E8 U+1F1E9',
  },
  CF: {
    code: 'CF',
    emoji: '🇨🇫',
    name: 'Central African Republic',
    unicode: 'U+1F1E8 U+1F1EB',
  },
  CG: {
    code: 'CG',
    emoji: '🇨🇬',
    name: 'Congo - Brazzaville',
    unicode: 'U+1F1E8 U+1F1EC',
  },
  CH: {
    code: 'CH',
    emoji: '🇨🇭',
    name: 'Switzerland',
    unicode: 'U+1F1E8 U+1F1ED',
  },
  CI: {
    code: 'CI',
    emoji: '🇨🇮',
    name: 'Côte d’Ivoire',
    unicode: 'U+1F1E8 U+1F1EE',
  },
  CK: {
    code: 'CK',
    emoji: '🇨🇰',
    name: 'Cook Islands',
    unicode: 'U+1F1E8 U+1F1F0',
  },
  CL: {
    code: 'CL',
    emoji: '🇨🇱',
    name: 'Chile',
    unicode: 'U+1F1E8 U+1F1F1',
  },
  CM: {
    code: 'CM',
    emoji: '🇨🇲',
    name: 'Cameroon',
    unicode: 'U+1F1E8 U+1F1F2',
  },
  CN: {
    code: 'CN',
    emoji: '🇨🇳',
    name: 'China',
    unicode: 'U+1F1E8 U+1F1F3',
  },
  CO: {
    code: 'CO',
    emoji: '🇨🇴',
    name: 'Colombia',
    unicode: 'U+1F1E8 U+1F1F4',
  },
  CP: {
    code: 'CP',
    emoji: '🇨🇵',
    name: 'Clipperton Island',
    unicode: 'U+1F1E8 U+1F1F5',
  },
  CR: {
    code: 'CR',
    emoji: '🇨🇷',
    name: 'Costa Rica',
    unicode: 'U+1F1E8 U+1F1F7',
  },
  CU: {
    code: 'CU',
    emoji: '🇨🇺',
    name: 'Cuba',
    unicode: 'U+1F1E8 U+1F1FA',
  },
  CV: {
    code: 'CV',
    emoji: '🇨🇻',
    name: 'Cape Verde',
    unicode: 'U+1F1E8 U+1F1FB',
  },
  CW: {
    code: 'CW',
    emoji: '🇨🇼',
    name: 'Curaçao',
    unicode: 'U+1F1E8 U+1F1FC',
  },
  CX: {
    code: 'CX',
    emoji: '🇨🇽',
    name: 'Christmas Island',
    unicode: 'U+1F1E8 U+1F1FD',
  },
  CY: {
    code: 'CY',
    emoji: '🇨🇾',
    name: 'Cyprus',
    unicode: 'U+1F1E8 U+1F1FE',
  },
  CZ: {
    code: 'CZ',
    emoji: '🇨🇿',
    name: 'Czechia',
    unicode: 'U+1F1E8 U+1F1FF',
  },
  DE: {
    code: 'DE',
    emoji: '🇩🇪',
    name: 'Germany',
    unicode: 'U+1F1E9 U+1F1EA',
  },
  DG: {
    code: 'DG',
    emoji: '🇩🇬',
    name: 'Diego Garcia',
    unicode: 'U+1F1E9 U+1F1EC',
  },
  DJ: {
    code: 'DJ',
    emoji: '🇩🇯',
    name: 'Djibouti',
    unicode: 'U+1F1E9 U+1F1EF',
  },
  DK: {
    code: 'DK',
    emoji: '🇩🇰',
    name: 'Denmark',
    unicode: 'U+1F1E9 U+1F1F0',
  },
  DM: {
    code: 'DM',
    emoji: '🇩🇲',
    name: 'Dominica',
    unicode: 'U+1F1E9 U+1F1F2',
  },
  DO: {
    code: 'DO',
    emoji: '🇩🇴',
    name: 'Dominican Republic',
    unicode: 'U+1F1E9 U+1F1F4',
  },
  DZ: {
    code: 'DZ',
    emoji: '🇩🇿',
    name: 'Algeria',
    unicode: 'U+1F1E9 U+1F1FF',
  },
  EA: {
    code: 'EA',
    emoji: '🇪🇦',
    name: 'Ceuta & Melilla',
    unicode: 'U+1F1EA U+1F1E6',
  },
  EC: {
    code: 'EC',
    emoji: '🇪🇨',
    name: 'Ecuador',
    unicode: 'U+1F1EA U+1F1E8',
  },
  EE: {
    code: 'EE',
    emoji: '🇪🇪',
    name: 'Estonia',
    unicode: 'U+1F1EA U+1F1EA',
  },
  EG: {
    code: 'EG',
    emoji: '🇪🇬',
    name: 'Egypt',
    unicode: 'U+1F1EA U+1F1EC',
  },
  EH: {
    code: 'EH',
    emoji: '🇪🇭',
    name: 'Western Sahara',
    unicode: 'U+1F1EA U+1F1ED',
  },
  ER: {
    code: 'ER',
    emoji: '🇪🇷',
    name: 'Eritrea',
    unicode: 'U+1F1EA U+1F1F7',
  },
  ES: {
    code: 'ES',
    emoji: '🇪🇸',
    name: 'Spain',
    unicode: 'U+1F1EA U+1F1F8',
  },
  ET: {
    code: 'ET',
    emoji: '🇪🇹',
    name: 'Ethiopia',
    unicode: 'U+1F1EA U+1F1F9',
  },
  EU: {
    code: 'EU',
    emoji: '🇪🇺',
    name: 'European Union',
    unicode: 'U+1F1EA U+1F1FA',
  },
  FI: {
    code: 'FI',
    emoji: '🇫🇮',
    name: 'Finland',
    unicode: 'U+1F1EB U+1F1EE',
  },
  FJ: {
    code: 'FJ',
    emoji: '🇫🇯',
    name: 'Fiji',
    unicode: 'U+1F1EB U+1F1EF',
  },
  FK: {
    code: 'FK',
    emoji: '🇫🇰',
    name: 'Falkland Islands',
    unicode: 'U+1F1EB U+1F1F0',
  },
  FM: {
    code: 'FM',
    emoji: '🇫🇲',
    name: 'Micronesia',
    unicode: 'U+1F1EB U+1F1F2',
  },
  FO: {
    code: 'FO',
    emoji: '🇫🇴',
    name: 'Faroe Islands',
    unicode: 'U+1F1EB U+1F1F4',
  },
  FR: {
    code: 'FR',
    emoji: '🇫🇷',
    name: 'France',
    unicode: 'U+1F1EB U+1F1F7',
  },
  GA: {
    code: 'GA',
    emoji: '🇬🇦',
    name: 'Gabon',
    unicode: 'U+1F1EC U+1F1E6',
  },
  GB: {
    code: 'GB',
    emoji: '🇬🇧',
    name: 'United Kingdom',
    unicode: 'U+1F1EC U+1F1E7',
  },
  GD: {
    code: 'GD',
    emoji: '🇬🇩',
    name: 'Grenada',
    unicode: 'U+1F1EC U+1F1E9',
  },
  GE: {
    code: 'GE',
    emoji: '🇬🇪',
    name: 'Georgia',
    unicode: 'U+1F1EC U+1F1EA',
  },
  GF: {
    code: 'GF',
    emoji: '🇬🇫',
    name: 'French Guiana',
    unicode: 'U+1F1EC U+1F1EB',
  },
  GG: {
    code: 'GG',
    emoji: '🇬🇬',
    name: 'Guernsey',
    unicode: 'U+1F1EC U+1F1EC',
  },
  GH: {
    code: 'GH',
    emoji: '🇬🇭',
    name: 'Ghana',
    unicode: 'U+1F1EC U+1F1ED',
  },
  GI: {
    code: 'GI',
    emoji: '🇬🇮',
    name: 'Gibraltar',
    unicode: 'U+1F1EC U+1F1EE',
  },
  GL: {
    code: 'GL',
    emoji: '🇬🇱',
    name: 'Greenland',
    unicode: 'U+1F1EC U+1F1F1',
  },
  GM: {
    code: 'GM',
    emoji: '🇬🇲',
    name: 'Gambia',
    unicode: 'U+1F1EC U+1F1F2',
  },
  GN: {
    code: 'GN',
    emoji: '🇬🇳',
    name: 'Guinea',
    unicode: 'U+1F1EC U+1F1F3',
  },
  GP: {
    code: 'GP',
    emoji: '🇬🇵',
    name: 'Guadeloupe',
    unicode: 'U+1F1EC U+1F1F5',
  },
  GQ: {
    code: 'GQ',
    emoji: '🇬🇶',
    name: 'Equatorial Guinea',
    unicode: 'U+1F1EC U+1F1F6',
  },
  GR: {
    code: 'GR',
    emoji: '🇬🇷',
    name: 'Greece',
    unicode: 'U+1F1EC U+1F1F7',
  },
  GS: {
    code: 'GS',
    emoji: '🇬🇸',
    name: 'South Georgia & South Sandwich Islands',
    unicode: 'U+1F1EC U+1F1F8',
  },
  GT: {
    code: 'GT',
    emoji: '🇬🇹',
    name: 'Guatemala',
    unicode: 'U+1F1EC U+1F1F9',
  },
  GU: {
    code: 'GU',
    emoji: '🇬🇺',
    name: 'Guam',
    unicode: 'U+1F1EC U+1F1FA',
  },
  GW: {
    code: 'GW',
    emoji: '🇬🇼',
    name: 'Guinea-Bissau',
    unicode: 'U+1F1EC U+1F1FC',
  },
  GY: {
    code: 'GY',
    emoji: '🇬🇾',
    name: 'Guyana',
    unicode: 'U+1F1EC U+1F1FE',
  },
  HK: {
    code: 'HK',
    emoji: '🇭🇰',
    name: 'Hong Kong SAR China',
    unicode: 'U+1F1ED U+1F1F0',
  },
  HM: {
    code: 'HM',
    emoji: '🇭🇲',
    name: 'Heard & McDonald Islands',
    unicode: 'U+1F1ED U+1F1F2',
  },
  HN: {
    code: 'HN',
    emoji: '🇭🇳',
    name: 'Honduras',
    unicode: 'U+1F1ED U+1F1F3',
  },
  HR: {
    code: 'HR',
    emoji: '🇭🇷',
    name: 'Croatia',
    unicode: 'U+1F1ED U+1F1F7',
  },
  HT: {
    code: 'HT',
    emoji: '🇭🇹',
    name: 'Haiti',
    unicode: 'U+1F1ED U+1F1F9',
  },
  HU: {
    code: 'HU',
    emoji: '🇭🇺',
    name: 'Hungary',
    unicode: 'U+1F1ED U+1F1FA',
  },
  IC: {
    code: 'IC',
    emoji: '🇮🇨',
    name: 'Canary Islands',
    unicode: 'U+1F1EE U+1F1E8',
  },
  ID: {
    code: 'ID',
    emoji: '🇮🇩',
    name: 'Indonesia',
    unicode: 'U+1F1EE U+1F1E9',
  },
  IE: {
    code: 'IE',
    emoji: '🇮🇪',
    name: 'Ireland',
    unicode: 'U+1F1EE U+1F1EA',
  },
  IL: {
    code: 'IL',
    emoji: '🇮🇱',
    name: 'Israel',
    unicode: 'U+1F1EE U+1F1F1',
  },
  IM: {
    code: 'IM',
    emoji: '🇮🇲',
    name: 'Isle of Man',
    unicode: 'U+1F1EE U+1F1F2',
  },
  IN: {
    code: 'IN',
    emoji: '🇮🇳',
    name: 'India',
    unicode: 'U+1F1EE U+1F1F3',
  },
  IO: {
    code: 'IO',
    emoji: '🇮🇴',
    name: 'British Indian Ocean Territory',
    unicode: 'U+1F1EE U+1F1F4',
  },
  IQ: {
    code: 'IQ',
    emoji: '🇮🇶',
    name: 'Iraq',
    unicode: 'U+1F1EE U+1F1F6',
  },
  IR: {
    code: 'IR',
    emoji: '🇮🇷',
    name: 'Iran',
    unicode: 'U+1F1EE U+1F1F7',
  },
  IS: {
    code: 'IS',
    emoji: '🇮🇸',
    name: 'Iceland',
    unicode: 'U+1F1EE U+1F1F8',
  },
  IT: {
    code: 'IT',
    emoji: '🇮🇹',
    name: 'Italy',
    unicode: 'U+1F1EE U+1F1F9',
  },
  JE: {
    code: 'JE',
    emoji: '🇯🇪',
    name: 'Jersey',
    unicode: 'U+1F1EF U+1F1EA',
  },
  JM: {
    code: 'JM',
    emoji: '🇯🇲',
    name: 'Jamaica',
    unicode: 'U+1F1EF U+1F1F2',
  },
  JO: {
    code: 'JO',
    emoji: '🇯🇴',
    name: 'Jordan',
    unicode: 'U+1F1EF U+1F1F4',
  },
  JP: {
    code: 'JP',
    emoji: '🇯🇵',
    name: 'Japan',
    unicode: 'U+1F1EF U+1F1F5',
  },
  KE: {
    code: 'KE',
    emoji: '🇰🇪',
    name: 'Kenya',
    unicode: 'U+1F1F0 U+1F1EA',
  },
  KG: {
    code: 'KG',
    emoji: '🇰🇬',
    name: 'Kyrgyzstan',
    unicode: 'U+1F1F0 U+1F1EC',
  },
  KH: {
    code: 'KH',
    emoji: '🇰🇭',
    name: 'Cambodia',
    unicode: 'U+1F1F0 U+1F1ED',
  },
  KI: {
    code: 'KI',
    emoji: '🇰🇮',
    name: 'Kiribati',
    unicode: 'U+1F1F0 U+1F1EE',
  },
  KM: {
    code: 'KM',
    emoji: '🇰🇲',
    name: 'Comoros',
    unicode: 'U+1F1F0 U+1F1F2',
  },
  KN: {
    code: 'KN',
    emoji: '🇰🇳',
    name: 'St. Kitts & Nevis',
    unicode: 'U+1F1F0 U+1F1F3',
  },
  KP: {
    code: 'KP',
    emoji: '🇰🇵',
    name: 'North Korea',
    unicode: 'U+1F1F0 U+1F1F5',
  },
  KR: {
    code: 'KR',
    emoji: '🇰🇷',
    name: 'South Korea',
    unicode: 'U+1F1F0 U+1F1F7',
  },
  KW: {
    code: 'KW',
    emoji: '🇰🇼',
    name: 'Kuwait',
    unicode: 'U+1F1F0 U+1F1FC',
  },
  KY: {
    code: 'KY',
    emoji: '🇰🇾',
    name: 'Cayman Islands',
    unicode: 'U+1F1F0 U+1F1FE',
  },
  KZ: {
    code: 'KZ',
    emoji: '🇰🇿',
    name: 'Kazakhstan',
    unicode: 'U+1F1F0 U+1F1FF',
  },
  LA: {
    code: 'LA',
    emoji: '🇱🇦',
    name: 'Laos',
    unicode: 'U+1F1F1 U+1F1E6',
  },
  LB: {
    code: 'LB',
    emoji: '🇱🇧',
    name: 'Lebanon',
    unicode: 'U+1F1F1 U+1F1E7',
  },
  LC: {
    code: 'LC',
    emoji: '🇱🇨',
    name: 'St. Lucia',
    unicode: 'U+1F1F1 U+1F1E8',
  },
  LI: {
    code: 'LI',
    emoji: '🇱🇮',
    name: 'Liechtenstein',
    unicode: 'U+1F1F1 U+1F1EE',
  },
  LK: {
    code: 'LK',
    emoji: '🇱🇰',
    name: 'Sri Lanka',
    unicode: 'U+1F1F1 U+1F1F0',
  },
  LR: {
    code: 'LR',
    emoji: '🇱🇷',
    name: 'Liberia',
    unicode: 'U+1F1F1 U+1F1F7',
  },
  LS: {
    code: 'LS',
    emoji: '🇱🇸',
    name: 'Lesotho',
    unicode: 'U+1F1F1 U+1F1F8',
  },
  LT: {
    code: 'LT',
    emoji: '🇱🇹',
    name: 'Lithuania',
    unicode: 'U+1F1F1 U+1F1F9',
  },
  LU: {
    code: 'LU',
    emoji: '🇱🇺',
    name: 'Luxembourg',
    unicode: 'U+1F1F1 U+1F1FA',
  },
  LV: {
    code: 'LV',
    emoji: '🇱🇻',
    name: 'Latvia',
    unicode: 'U+1F1F1 U+1F1FB',
  },
  LY: {
    code: 'LY',
    emoji: '🇱🇾',
    name: 'Libya',
    unicode: 'U+1F1F1 U+1F1FE',
  },
  MA: {
    code: 'MA',
    emoji: '🇲🇦',
    name: 'Morocco',
    unicode: 'U+1F1F2 U+1F1E6',
  },
  MC: {
    code: 'MC',
    emoji: '🇲🇨',
    name: 'Monaco',
    unicode: 'U+1F1F2 U+1F1E8',
  },
  MD: {
    code: 'MD',
    emoji: '🇲🇩',
    name: 'Moldova',
    unicode: 'U+1F1F2 U+1F1E9',
  },
  ME: {
    code: 'ME',
    emoji: '🇲🇪',
    name: 'Montenegro',
    unicode: 'U+1F1F2 U+1F1EA',
  },
  MF: {
    code: 'MF',
    emoji: '🇲🇫',
    name: 'St. Martin',
    unicode: 'U+1F1F2 U+1F1EB',
  },
  MG: {
    code: 'MG',
    emoji: '🇲🇬',
    name: 'Madagascar',
    unicode: 'U+1F1F2 U+1F1EC',
  },
  MH: {
    code: 'MH',
    emoji: '🇲🇭',
    name: 'Marshall Islands',
    unicode: 'U+1F1F2 U+1F1ED',
  },
  MK: {
    code: 'MK',
    emoji: '🇲🇰',
    name: 'Macedonia',
    unicode: 'U+1F1F2 U+1F1F0',
  },
  ML: {
    code: 'ML',
    emoji: '🇲🇱',
    name: 'Mali',
    unicode: 'U+1F1F2 U+1F1F1',
  },
  MM: {
    code: 'MM',
    emoji: '🇲🇲',
    name: 'Myanmar (Burma)',
    unicode: 'U+1F1F2 U+1F1F2',
  },
  MN: {
    code: 'MN',
    emoji: '🇲🇳',
    name: 'Mongolia',
    unicode: 'U+1F1F2 U+1F1F3',
  },
  MO: {
    code: 'MO',
    emoji: '🇲🇴',
    name: 'Macau SAR China',
    unicode: 'U+1F1F2 U+1F1F4',
  },
  MP: {
    code: 'MP',
    emoji: '🇲🇵',
    name: 'Northern Mariana Islands',
    unicode: 'U+1F1F2 U+1F1F5',
  },
  MQ: {
    code: 'MQ',
    emoji: '🇲🇶',
    name: 'Martinique',
    unicode: 'U+1F1F2 U+1F1F6',
  },
  MR: {
    code: 'MR',
    emoji: '🇲🇷',
    name: 'Mauritania',
    unicode: 'U+1F1F2 U+1F1F7',
  },
  MS: {
    code: 'MS',
    emoji: '🇲🇸',
    name: 'Montserrat',
    unicode: 'U+1F1F2 U+1F1F8',
  },
  MT: {
    code: 'MT',
    emoji: '🇲🇹',
    name: 'Malta',
    unicode: 'U+1F1F2 U+1F1F9',
  },
  MU: {
    code: 'MU',
    emoji: '🇲🇺',
    name: 'Mauritius',
    unicode: 'U+1F1F2 U+1F1FA',
  },
  MV: {
    code: 'MV',
    emoji: '🇲🇻',
    name: 'Maldives',
    unicode: 'U+1F1F2 U+1F1FB',
  },
  MW: {
    code: 'MW',
    emoji: '🇲🇼',
    name: 'Malawi',
    unicode: 'U+1F1F2 U+1F1FC',
  },
  MX: {
    code: 'MX',
    emoji: '🇲🇽',
    name: 'Mexico',
    unicode: 'U+1F1F2 U+1F1FD',
  },
  MY: {
    code: 'MY',
    emoji: '🇲🇾',
    name: 'Malaysia',
    unicode: 'U+1F1F2 U+1F1FE',
  },
  MZ: {
    code: 'MZ',
    emoji: '🇲🇿',
    name: 'Mozambique',
    unicode: 'U+1F1F2 U+1F1FF',
  },
  NA: {
    code: 'NA',
    emoji: '🇳🇦',
    name: 'Namibia',
    unicode: 'U+1F1F3 U+1F1E6',
  },
  NC: {
    code: 'NC',
    emoji: '🇳🇨',
    name: 'New Caledonia',
    unicode: 'U+1F1F3 U+1F1E8',
  },
  NE: {
    code: 'NE',
    emoji: '🇳🇪',
    name: 'Niger',
    unicode: 'U+1F1F3 U+1F1EA',
  },
  NF: {
    code: 'NF',
    emoji: '🇳🇫',
    name: 'Norfolk Island',
    unicode: 'U+1F1F3 U+1F1EB',
  },
  NG: {
    code: 'NG',
    emoji: '🇳🇬',
    name: 'Nigeria',
    unicode: 'U+1F1F3 U+1F1EC',
  },
  NI: {
    code: 'NI',
    emoji: '🇳🇮',
    name: 'Nicaragua',
    unicode: 'U+1F1F3 U+1F1EE',
  },
  NL: {
    code: 'NL',
    emoji: '🇳🇱',
    name: 'Netherlands',
    unicode: 'U+1F1F3 U+1F1F1',
  },
  NO: {
    code: 'NO',
    emoji: '🇳🇴',
    name: 'Norway',
    unicode: 'U+1F1F3 U+1F1F4',
  },
  NP: {
    code: 'NP',
    emoji: '🇳🇵',
    name: 'Nepal',
    unicode: 'U+1F1F3 U+1F1F5',
  },
  NR: {
    code: 'NR',
    emoji: '🇳🇷',
    name: 'Nauru',
    unicode: 'U+1F1F3 U+1F1F7',
  },
  NU: {
    code: 'NU',
    emoji: '🇳🇺',
    name: 'Niue',
    unicode: 'U+1F1F3 U+1F1FA',
  },
  NZ: {
    code: 'NZ',
    emoji: '🇳🇿',
    name: 'New Zealand',
    unicode: 'U+1F1F3 U+1F1FF',
  },
  OM: {
    code: 'OM',
    emoji: '🇴🇲',
    name: 'Oman',
    unicode: 'U+1F1F4 U+1F1F2',
  },
  PA: {
    code: 'PA',
    emoji: '🇵🇦',
    name: 'Panama',
    unicode: 'U+1F1F5 U+1F1E6',
  },
  PE: {
    code: 'PE',
    emoji: '🇵🇪',
    name: 'Peru',
    unicode: 'U+1F1F5 U+1F1EA',
  },
  PF: {
    code: 'PF',
    emoji: '🇵🇫',
    name: 'French Polynesia',
    unicode: 'U+1F1F5 U+1F1EB',
  },
  PG: {
    code: 'PG',
    emoji: '🇵🇬',
    name: 'Papua New Guinea',
    unicode: 'U+1F1F5 U+1F1EC',
  },
  PH: {
    code: 'PH',
    emoji: '🇵🇭',
    name: 'Philippines',
    unicode: 'U+1F1F5 U+1F1ED',
  },
  PK: {
    code: 'PK',
    emoji: '🇵🇰',
    name: 'Pakistan',
    unicode: 'U+1F1F5 U+1F1F0',
  },
  PL: {
    code: 'PL',
    emoji: '🇵🇱',
    name: 'Poland',
    unicode: 'U+1F1F5 U+1F1F1',
  },
  PM: {
    code: 'PM',
    emoji: '🇵🇲',
    name: 'St. Pierre & Miquelon',
    unicode: 'U+1F1F5 U+1F1F2',
  },
  PN: {
    code: 'PN',
    emoji: '🇵🇳',
    name: 'Pitcairn Islands',
    unicode: 'U+1F1F5 U+1F1F3',
  },
  PR: {
    code: 'PR',
    emoji: '🇵🇷',
    name: 'Puerto Rico',
    unicode: 'U+1F1F5 U+1F1F7',
  },
  PS: {
    code: 'PS',
    emoji: '🇵🇸',
    name: 'Palestinian Territories',
    unicode: 'U+1F1F5 U+1F1F8',
  },
  PT: {
    code: 'PT',
    emoji: '🇵🇹',
    name: 'Portugal',
    unicode: 'U+1F1F5 U+1F1F9',
  },
  PW: {
    code: 'PW',
    emoji: '🇵🇼',
    name: 'Palau',
    unicode: 'U+1F1F5 U+1F1FC',
  },
  PY: {
    code: 'PY',
    emoji: '🇵🇾',
    name: 'Paraguay',
    unicode: 'U+1F1F5 U+1F1FE',
  },
  QA: {
    code: 'QA',
    emoji: '🇶🇦',
    name: 'Qatar',
    unicode: 'U+1F1F6 U+1F1E6',
  },
  RE: {
    code: 'RE',
    emoji: '🇷🇪',
    name: 'Réunion',
    unicode: 'U+1F1F7 U+1F1EA',
  },
  RO: {
    code: 'RO',
    emoji: '🇷🇴',
    name: 'Romania',
    unicode: 'U+1F1F7 U+1F1F4',
  },
  RS: {
    code: 'RS',
    emoji: '🇷🇸',
    name: 'Serbia',
    unicode: 'U+1F1F7 U+1F1F8',
  },
  RU: {
    code: 'RU',
    emoji: '🇷🇺',
    name: 'Russia',
    unicode: 'U+1F1F7 U+1F1FA',
  },
  RW: {
    code: 'RW',
    emoji: '🇷🇼',
    name: 'Rwanda',
    unicode: 'U+1F1F7 U+1F1FC',
  },
  SA: {
    code: 'SA',
    emoji: '🇸🇦',
    name: 'Saudi Arabia',
    unicode: 'U+1F1F8 U+1F1E6',
  },
  SB: {
    code: 'SB',
    emoji: '🇸🇧',
    name: 'Solomon Islands',
    unicode: 'U+1F1F8 U+1F1E7',
  },
  SC: {
    code: 'SC',
    emoji: '🇸🇨',
    name: 'Seychelles',
    unicode: 'U+1F1F8 U+1F1E8',
  },
  SD: {
    code: 'SD',
    emoji: '🇸🇩',
    name: 'Sudan',
    unicode: 'U+1F1F8 U+1F1E9',
  },
  SE: {
    code: 'SE',
    emoji: '🇸🇪',
    name: 'Sweden',
    unicode: 'U+1F1F8 U+1F1EA',
  },
  SG: {
    code: 'SG',
    emoji: '🇸🇬',
    name: 'Singapore',
    unicode: 'U+1F1F8 U+1F1EC',
  },
  SH: {
    code: 'SH',
    emoji: '🇸🇭',
    name: 'St. Helena',
    unicode: 'U+1F1F8 U+1F1ED',
  },
  SI: {
    code: 'SI',
    emoji: '🇸🇮',
    name: 'Slovenia',
    unicode: 'U+1F1F8 U+1F1EE',
  },
  SJ: {
    code: 'SJ',
    emoji: '🇸🇯',
    name: 'Svalbard & Jan Mayen',
    unicode: 'U+1F1F8 U+1F1EF',
  },
  SK: {
    code: 'SK',
    emoji: '🇸🇰',
    name: 'Slovakia',
    unicode: 'U+1F1F8 U+1F1F0',
  },
  SL: {
    code: 'SL',
    emoji: '🇸🇱',
    name: 'Sierra Leone',
    unicode: 'U+1F1F8 U+1F1F1',
  },
  SM: {
    code: 'SM',
    emoji: '🇸🇲',
    name: 'San Marino',
    unicode: 'U+1F1F8 U+1F1F2',
  },
  SN: {
    code: 'SN',
    emoji: '🇸🇳',
    name: 'Senegal',
    unicode: 'U+1F1F8 U+1F1F3',
  },
  SO: {
    code: 'SO',
    emoji: '🇸🇴',
    name: 'Somalia',
    unicode: 'U+1F1F8 U+1F1F4',
  },
  SR: {
    code: 'SR',
    emoji: '🇸🇷',
    name: 'Suriname',
    unicode: 'U+1F1F8 U+1F1F7',
  },
  SS: {
    code: 'SS',
    emoji: '🇸🇸',
    name: 'South Sudan',
    unicode: 'U+1F1F8 U+1F1F8',
  },
  ST: {
    code: 'ST',
    emoji: '🇸🇹',
    name: 'São Tomé & Príncipe',
    unicode: 'U+1F1F8 U+1F1F9',
  },
  SV: {
    code: 'SV',
    emoji: '🇸🇻',
    name: 'El Salvador',
    unicode: 'U+1F1F8 U+1F1FB',
  },
  SX: {
    code: 'SX',
    emoji: '🇸🇽',
    name: 'Sint Maarten',
    unicode: 'U+1F1F8 U+1F1FD',
  },
  SY: {
    code: 'SY',
    emoji: '🇸🇾',
    name: 'Syria',
    unicode: 'U+1F1F8 U+1F1FE',
  },
  SZ: {
    code: 'SZ',
    emoji: '🇸🇿',
    name: 'Swaziland',
    unicode: 'U+1F1F8 U+1F1FF',
  },
  TA: {
    code: 'TA',
    emoji: '🇹🇦',
    name: 'Tristan da Cunha',
    unicode: 'U+1F1F9 U+1F1E6',
  },
  TC: {
    code: 'TC',
    emoji: '🇹🇨',
    name: 'Turks & Caicos Islands',
    unicode: 'U+1F1F9 U+1F1E8',
  },
  TD: {
    code: 'TD',
    emoji: '🇹🇩',
    name: 'Chad',
    unicode: 'U+1F1F9 U+1F1E9',
  },
  TF: {
    code: 'TF',
    emoji: '🇹🇫',
    name: 'French Southern Territories',
    unicode: 'U+1F1F9 U+1F1EB',
  },
  TG: {
    code: 'TG',
    emoji: '🇹🇬',
    name: 'Togo',
    unicode: 'U+1F1F9 U+1F1EC',
  },
  TH: {
    code: 'TH',
    emoji: '🇹🇭',
    name: 'Thailand',
    unicode: 'U+1F1F9 U+1F1ED',
  },
  TJ: {
    code: 'TJ',
    emoji: '🇹🇯',
    name: 'Tajikistan',
    unicode: 'U+1F1F9 U+1F1EF',
  },
  TK: {
    code: 'TK',
    emoji: '🇹🇰',
    name: 'Tokelau',
    unicode: 'U+1F1F9 U+1F1F0',
  },
  TL: {
    code: 'TL',
    emoji: '🇹🇱',
    name: 'Timor-Leste',
    unicode: 'U+1F1F9 U+1F1F1',
  },
  TM: {
    code: 'TM',
    emoji: '🇹🇲',
    name: 'Turkmenistan',
    unicode: 'U+1F1F9 U+1F1F2',
  },
  TN: {
    code: 'TN',
    emoji: '🇹🇳',
    name: 'Tunisia',
    unicode: 'U+1F1F9 U+1F1F3',
  },
  TO: {
    code: 'TO',
    emoji: '🇹🇴',
    name: 'Tonga',
    unicode: 'U+1F1F9 U+1F1F4',
  },
  TR: {
    code: 'TR',
    emoji: '🇹🇷',
    name: 'Turkey',
    unicode: 'U+1F1F9 U+1F1F7',
  },
  TT: {
    code: 'TT',
    emoji: '🇹🇹',
    name: 'Trinidad & Tobago',
    unicode: 'U+1F1F9 U+1F1F9',
  },
  TV: {
    code: 'TV',
    emoji: '🇹🇻',
    name: 'Tuvalu',
    unicode: 'U+1F1F9 U+1F1FB',
  },
  TW: {
    code: 'TW',
    emoji: '🇹🇼',
    name: 'Taiwan',
    unicode: 'U+1F1F9 U+1F1FC',
  },
  TZ: {
    code: 'TZ',
    emoji: '🇹🇿',
    name: 'Tanzania',
    unicode: 'U+1F1F9 U+1F1FF',
  },
  UA: {
    code: 'UA',
    emoji: '🇺🇦',
    name: 'Ukraine',
    unicode: 'U+1F1FA U+1F1E6',
  },
  UG: {
    code: 'UG',
    emoji: '🇺🇬',
    name: 'Uganda',
    unicode: 'U+1F1FA U+1F1EC',
  },
  UM: {
    code: 'UM',
    emoji: '🇺🇲',
    name: 'U.S. Outlying Islands',
    unicode: 'U+1F1FA U+1F1F2',
  },
  UN: {
    code: 'UN',
    emoji: '🇺🇳',
    name: 'United Nations',
    unicode: 'U+1F1FA U+1F1F3',
  },
  US: {
    code: 'US',
    emoji: '🇺🇸',
    name: 'United States',
    unicode: 'U+1F1FA U+1F1F8',
  },
  UY: {
    code: 'UY',
    emoji: '🇺🇾',
    name: 'Uruguay',
    unicode: 'U+1F1FA U+1F1FE',
  },
  UZ: {
    code: 'UZ',
    emoji: '🇺🇿',
    name: 'Uzbekistan',
    unicode: 'U+1F1FA U+1F1FF',
  },
  VA: {
    code: 'VA',
    emoji: '🇻🇦',
    name: 'Vatican City',
    unicode: 'U+1F1FB U+1F1E6',
  },
  VC: {
    code: 'VC',
    emoji: '🇻🇨',
    name: 'St. Vincent & Grenadines',
    unicode: 'U+1F1FB U+1F1E8',
  },
  VE: {
    code: 'VE',
    emoji: '🇻🇪',
    name: 'Venezuela',
    unicode: 'U+1F1FB U+1F1EA',
  },
  VG: {
    code: 'VG',
    emoji: '🇻🇬',
    name: 'British Virgin Islands',
    unicode: 'U+1F1FB U+1F1EC',
  },
  VI: {
    code: 'VI',
    emoji: '🇻🇮',
    name: 'U.S. Virgin Islands',
    unicode: 'U+1F1FB U+1F1EE',
  },
  VN: {
    code: 'VN',
    emoji: '🇻🇳',
    name: 'Vietnam',
    unicode: 'U+1F1FB U+1F1F3',
  },
  VU: {
    code: 'VU',
    emoji: '🇻🇺',
    name: 'Vanuatu',
    unicode: 'U+1F1FB U+1F1FA',
  },
  WF: {
    code: 'WF',
    emoji: '🇼🇫',
    name: 'Wallis & Futuna',
    unicode: 'U+1F1FC U+1F1EB',
  },
  WS: {
    code: 'WS',
    emoji: '🇼🇸',
    name: 'Samoa',
    unicode: 'U+1F1FC U+1F1F8',
  },
  XK: {
    code: 'XK',
    emoji: '🇽🇰',
    name: 'Kosovo',
    unicode: 'U+1F1FD U+1F1F0',
  },
  YE: {
    code: 'YE',
    emoji: '🇾🇪',
    name: 'Yemen',
    unicode: 'U+1F1FE U+1F1EA',
  },
  YT: {
    code: 'YT',
    emoji: '🇾🇹',
    name: 'Mayotte',
    unicode: 'U+1F1FE U+1F1F9',
  },
  ZA: {
    code: 'ZA',
    emoji: '🇿🇦',
    name: 'South Africa',
    unicode: 'U+1F1FF U+1F1E6',
  },
  ZM: {
    code: 'ZM',
    emoji: '🇿🇲',
    name: 'Zambia',
    unicode: 'U+1F1FF U+1F1F2',
  },
  ZW: {
    code: 'ZW',
    emoji: '🇿🇼',
    name: 'Zimbabwe',
    unicode: 'U+1F1FF U+1F1FC',
  },
};

export function getCountryFlagWithName(countryCode: string) {
  const country = countries[countryCode];
  return country ? `${country.emoji} ${country.name}` : '';
}
